### ISSUE TITLE
[Viramate only] First skills broken depending on settings

### ISSUE THREAD

**Issue by MegaBlues** [Masuzu/ZooeyBot#1016]
In version 3.5.1, it seems as if scripting any character's Skill 1 while having Viramate enabled in the .ini will make Zooeybot hang indefinitely.

**Comment by elp-l** [comment]
Also experiencing this, Zooey is stalling when a script attempts "Q" (first slot) skill usage.  No error, no crash.  Recreated on use of Jeanne d'Arc (dark), Seox, and Djeeta's first skill slot.  Script previously worked on (non-Djeeta) skills using version 3.33.

**Comment by CorrinKrow** [comment]
Yes that option is enabled.

**Comment by elp-l** [comment]
Disabling that option fixes this issue, though I have previously preferred having it enabled.

The way I heard it, the summon confirm and the 1Q skills are now checked for actually having been clicked, added to the list of unsafe to hotkey elements such as the attack button.  I don't know whether it's specifically character slot 1 skill slot 1 that is now problematic, or if it's Djeeta skill slot 1.  If it's the latter, we'd have to replace all skill inputs for first slot skills with proper UI clicks (as Zooey 3.5.1 does) in order to be protected in the event of Djeeta moving slots in battle, meaning it should be required for Zooey usage to disable that option.

For what it's worth, if I tactical relocation Djeeta with any other character, all hotkeys appear to work as they used to before the change, both on the character now in character slot 1 and Djeeta in her new slot.  This might be a problem for Viramate.

**Comment by zappky** [comment]
I am also having the problem of Bot stuck at trying to clicking first skill, regardless of whether it is MC or not. Tried with Mech first and Seox first. The bot will just say its blue text of "Use skill at position 1".

It is sort of a temporary fix when Disabling the "Highlight Quick Panel" option.

**Comment by Masuzu** [comment]
Thank you for the confirmation @zappky , that will do for now then as it mitigates the "issue".
