### ISSUE TITLE
"oops, something went wrong" when processing main account in slave mode

### ISSUE THREAD

**Issue by hfcata** [Masuzu/ZooeyBot#1041]
Slave mode starts without problems and the slave script works fine. Zooey then reports an error and does not do anything on the main account except refresh. After refreshing 2 times zooey will bring the mouse to completely wrong locations can get stuck forever. 

![image](https://user-images.githubusercontent.com/47430232/52435696-5ce9bc00-2b0a-11e9-8e23-6bb508383239.png)

**Comment by hfcata** [comment]
I was able to get it to work by running the slave extension using another chrome profile (instead of running it in incognito). 
![image](https://user-images.githubusercontent.com/47430232/52436708-e00c1180-2b0c-11e9-9bcb-f7c67649e74f.png)

**Comment by zappky** [comment]
I am not sure if this is relevant to your problem but ...
This just my guess, i think slave mode is a bit wonky due to not able to always synchronize the inter state of the two accounts. Which end up causing these weird situation, even maybe yours too.

It is like almost every time i use slave mode, it presents new issue.

Recently, i encountered weird things such as using pot on the wrong acc, or wrong skill.
The mouse pointer cannot press the "use" button on slave acc for pot refill until a few attempts later  

The most prominent for me is repeatedly refreshing a window, be it main or slave. 
I suppose it is trying to detect(see) whether by refreshing that acc it will shows the game state the bot is expecting but it doesn't. End up it just keep refreshing.
This usually occurs after the battle is over. at the result screen.
During the lobby screen, it can happen too. 

For now, if the problem isn't too serious ,just hang tight and wait for reply from Masuzu.
