### ISSUE TITLE
Proving Grounds, Bot Crashes after 1st battle

### ISSUE THREAD

**Issue by CorrinKrow** [Masuzu/ZooeyBot#1045]
currently using newest version v3.6.2. The bot will crash immediately after the first battle in proving grounds as referenced in #1043

**Comment by Jinko78** [comment]
Yup still crashing for me also.

**Comment by CorrinKrow** [comment]
@Jinko78 sorry which text and url are you referencing if you mean the setup in #1044 ive tried it and the bot still crashes after the first battle

**Comment by granblue5eva** [comment]
Having same issue, also tried copying set up #1044 but Zoey still crashes after first battle. Also #1044 seems to have a minor error - EX+ costs 40 ap, not 50?

**Comment by Jinko78** [comment]
Yea sorry I meant #1044 
Well it was working for me, but now its not again, maybe its an issue with latency ?

**Comment by GranblueOjisan** [comment]
same problem here
I'm using JP version and live in Japan
I tried #1044 set up and still crash for me

**Comment by sam-f-owens** [comment]
Also problem here. Difficulty is Ex+, fails after first battle. Last message on the console is Selecting party
![screenshot 2019-02-09 13 54 10](https://user-images.githubusercontent.com/35882705/52527818-0c41a280-2c73-11e9-8f67-cee2070fe4a7.png)

 .ini configuration. 
```
[TreasureEventMode]
Enabled=true
# Url of the event page. The URL of the June 2017 dark GW is given as an example.
TreasureEventUrl=http://game.granbluefantasy.jp/#event/sequenceraid002/supporter/1400203
# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'impossible' (introduced since the "Right Behind You" event), 'xeno-raid' (for the level 100 Xeno raid), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100, proving-grounds (https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode#proving-grounds)
Difficulty=proving-grounds
# Action point cost of the quest you are trying to start
ActionPointCost=40
TreasureEventModeScript=Scripts/pwind.lua
```

**Comment by sam-f-owens** [comment]
Same problem. After first battle, crashes when it returns to party selection/start screen. Last message on console is 'Selecting party'

.ini configuration
[TreasureEventMode]
Enabled=true
# Url of the event page. The URL of the June 2017 dark GW is given as an example.
TreasureEventUrl=http://game.granbluefantasy.jp/#event/sequenceraid002/supporter/1400203
# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'impossible' (introduced since the "Right Behind You" event), 'xeno-raid' (for the level 100 Xeno raid), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100, proving-grounds (https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode#proving-grounds)
Difficulty=proving-grounds
# Action point cost of the quest you are trying to start
ActionPointCost=40
TreasureEventModeScript=Scripts/pwind.lua

**Comment by xerance** [comment]
+1, same issue

**Comment by MegaBlues** [comment]
Uploading the .cmd window for the information. The bot crashes before the party selection window loads at all, immediately after the results page is passed.

Also, the bot doesn't recognize '4' as a valid setting for selecting a party. If a Preferred Party is set to 4, it will default to 3.

![image](https://user-images.githubusercontent.com/39666963/52528237-7ffda280-2ca7-11e9-9919-ac4989f35560.png)

**Comment by FatherOJ** [comment]
+1, crashing after 1st battle too

**Comment by Jinko78** [comment]
Think I got it working.
Try pasting this to the top of your ini

[General]
# Possible values: jp, en. Default to en when the string is malformed. Please make sure that your configuration file is encoded using UTF8 if you use non Unicode characters.
Language=en
MaxPageLoadDelayInMsBeforeRetry=5000
# Maximum amount of time Zooey will wait for an expected event to occur (for instance, the attack button appearance) before triggering the fallback policy.
MaxTriggerDelayInMsBeforeFallback=5000
# Maximum delay before an action is deemed to have failed due to a lack of response from the GBF servers
MaxResponseDelayInMs=5000
# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=5000

**Comment by Nao-Tomori** [comment]
Same thing is happening also, immediate crash after 1st battle.

**Comment by Jinko78** [comment]
I switched to chrome instead of chromium and it's working now, I'd check your chromium version if you haven't already.

**Comment by CorrinKrow** [comment]
Tried in Chrome version 72.0.3626.96 and it still doesnt work

**Comment by xerance** [comment]
chrome seems to have fixed it for me, swapped from chromium to the latest chrome version 64bits

**Comment by MegaBlues** [comment]
Yep, Chrome Version 72.0.3626.96 seems to have solved the problem, interestingly enough.

**Comment by CorrinKrow** [comment]
Running in chrome, the bot still crashes, but it seems to be a latency issue. Is it possible to add a delay after the first battle?

**Comment by Koraxor** [comment]
I had this issue as well and I seem to have just fixed it for myself. There must have been some line added to the .ini at some point that had to do with this, I grabbed the zooeybot.ini out of the latest download and completely redid the config and it's working fine now. Kind of the problem with having no formal GUI and having to use these .ini is that I sure as hell don't want to have to go through and redo every one of them (especially since I have folders and folders of inis for every event and primal, farm, etc etc) with every update, and it leads to these kind of issues cause others probably don't either. That's not to say it's bad, cause it's always good to get more options, and have Masuzu keep working on the bot, but some middle ground would be cool, either way, I assume this should solve the problem if you all do that.

**Comment by GranblueOjisan** [comment]
Chrome version:72.0.3626.96 64bit
Zooeybot language setting:JP
Latency:very low(live in Japan)

Okay I grabbed newest zooeybot and redid config ... just copied lua scripts from old zooeybot folder.
but bot still crashes. I don't know what should I do now

**Comment by Einhalkzt** [comment]
i already tried the recommended chromium 67.0.3366.0 and the newest chromium 74.0.3702.0
both still crash 80% of the times. The other 20% is, it working for like 1-3 rounds before crashing after 1st battle.
Tried it with a fresh zooeybot with only the Scripts folder from the older version, still the same behaviour.

**Comment by MegaBlues** [comment]
Adding a tip, turning off the combat reload might do it?

**Comment by sam-f-owens** [comment]
That's the one. Changing this line to false fixed it here. 
```
# This saves up some precious seconds and that is what every MVP racer does.
ReloadPageOnLastBattle=true
```

**Comment by Einhalkzt** [comment]
yeah disabling reload on last battle seems to fix it, hasnt crashed once in a while

**Comment by i-Grey** [comment]
@Masuzu

**Comment by jinoga** [comment]
1run is fine but 2run Bot Crashes after 1 battle too

**Comment by niayyy** [comment]
SAME HERE, CRASHED AFTER FINISHING THE 1ST BATTLE

**Comment by Chololoco13** [comment]
Same problem

**Comment by Masuzu** [comment]
Looking into it.

**Comment by Masuzu** [comment]
I apologize for the delay in the response. A mitigation for the aforementioned issues was added in v3.6.3.

**Comment by minotopo2000** [comment]
Still crashing even with new version for me

**Comment by catly1** [comment]
Same with 3.6.3.
Crashes after selecting party.

**Comment by Sundaerae** [comment]
Still crashing on the 2nd set

**Comment by appleloli** [comment]
Sometimes it will hang on a skill for the second battle (which happened in 3.6.1) otherwise it will crash before starting the second battle.

**Comment by niayyy** [comment]
same problem using 3.6.3

**Comment by Masuzu** [comment]
It might try to click too soon on the start button after returning to the party selection screen. I will add additional log messages.
