### ISSUE TITLE
Lua Script Parse 

### ISSUE THREAD

**Issue by sparkster48** [Masuzu/ZooeyBot#1080]
I am brand new to ZooeyBot and wanted to start working on LUA scripts for the Campaign Exclusive event. After looking through some of the test code on the website I figured I could throw something together with my limited knowledge. All of my scripts I some manage to run into a failure to Parse but on this one specifically I cannot see where I went wrong--I did something very similar to one I found online. I fixed the other errors and once I got this one (I am assuming it is referring to line 17) I couldn't tell where I went wrong. I may just be a syntax issue, my knowledge of coding is very small. 
Thank you in advance!
![Screenshot_4](https://user-images.githubusercontent.com/47395433/54611300-0b97eb00-4a2d-11e9-839b-c7fe85c06edc.png)

**Comment by stn232** [comment]
delete "end"

**Comment by sparkster48** [comment]
> delete "end"
Thank you stn232 that worked and got rid of the error! May I ask why? All the other code I saw had end so I figured it would be related to the attack action. 
I have another issue where it wont click ok anymore but I will try to solve that then ask around.

**Comment by zappky** [comment]
Spark, this is simply a simple lua scripting problem.  It will serve you well if you study how lua works. 

Simply put, the "end" here isnt part of zooey bot, it is part lua scripting, it doesn't mean "end of script" 
Looking up on lua documentation, End is use to signify an "end" for a block of statement such as.
If statement. 
while statement
Function

The other codes you mention are probably using those statement and thus seems like it ended with "end" word in fact is is for those statement and how to signify the end of file/script. Ironically, <eof> in that error message means end of file.
Anyway, once you learn more about lua scripting, you would be able to script more comphrehensive script to handle even bigger task such as nm100 bot and with much greater precision. 
So dont slack off on basic. Good luck.

Lastly, what do you mean by the bot doesnt click "Ok" anymore?  If the bot crashes due to wrong sytnax then yea, of course, otherwise, the bot should be able to navigate the game fine.

**Comment by sparkster48** [comment]
Zappky thank you for the response I will definitely begin to look into learning Lua scripting as a whole! 
As far as it no longer clicking "Ok" I managed to fix that some how--I think it needed a good restart. 

Issue has been solved so I am going to close this! Thank you all!
