### ISSUE TITLE
Party Selection issue

### ISSUE THREAD

**Issue by froznkamui** [Masuzu/ZooeyBot#1097]
Apparently I already set my preferred party on zooey.ini, or even in party selection lua
and for some reason it messed up sometimes if you dont have any AP left and proceed to auto-select party and now it messed up my party rooster, grid and summons, anyone having this trouble ?

**Comment by Zbterr** [comment]
Yup, me too, i just leave it like that and adjust the script to the new party, problem is that the newly “auto” party is waaaay worse than the one i use

**Comment by MegaBlues** [comment]
I recently had an issue where Zooeybot changed my default party when selecting a quest, which is a major issue.

**Comment by SunStrider8420** [comment]
Same problem.

Earlier today it randomly changed my parties from slot 2 to 3 to 4.
Fixed it by making all slots in that row the same characters, then later on it went and actually switched out characters for me instead, wtf?

**Comment by MegaBlues** [comment]
So, I found the problem and solution. The issue is that, with the recent changes, Zooeybot continues to click the summons regardless of any set delays until the party selection menu turns up. This means that, on the chance where the summon selection and party selection overlap, Zooeybot can click a party while it means to click a summon, which is bad.

However, using party selections options can mitigate this, since it'll re-select the correct party after selecting the summon, even if the correct party is clicked off of. Here's party of my daily hosting schedule, and a link to the relevant .lua settings FAQ.

```
--Tiamat Hard+
SetLuaScript("Scripts/HardModeMagna.lua")
SetPreferredSummons("Kaguya, White Rabbit, Black Rabbit, Nobiyo")
RerollSummonWhenNoPreferredSummonWasFound=true
SetPreferredPartyGroup(1)
SetPreferredPartyDeck(1)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/305011/1", 0, 1)
```

[https://github.com/Masuzu/ZooeyBot/wiki/Party-selection](url)

**Comment by Beedrills** [comment]
The problem isn't that it changes which party is fighting; the problem is that the auto-select button changes the characters, weapon page, and summons in the party itself. I tried using my ad-blocker to disable the auto-select button, but it doesn't stick for me. It's especially a pain while trying to farm slime search to level Vampy.

**Comment by Alissa1122** [comment]
Is this auto-select issue fixed at new version?
Cause I didn’t see patch note address this yet, hope Masuzu can look into this problem soon

**Comment by Masuzu** [comment]
Hello all,
Please correct me if I am wrong, this was due to clicking repeatedly on the summon to select, with very little delay between each click. That delay was significantly increased in the last release, which should not lead anymore to that annoying issue.

**Comment by MegaBlues** [comment]
I personally haven't run into the issue at all since the fix, but it could theoretically be possible if your ping and the delay time line up in a way where a re-click to select a summon happens immediately before the confirmation/party selection menu pops up.

Is it possible to tie the delay for re-clicking summons to `MaxResponseDelayInMs` ?
