### ISSUE TITLE
Zooey Bot Keeps moving the cursor out of bound

### ISSUE THREAD

**Issue by Kokkujin** [Masuzu/ZooeyBot#1100]
Everytime i give it a specific summon to select and it is in the middle of the page, somehow it over scrolls and decide to click on the google address bar, cause the page to reload and doing the same thing until the sound prompt appear.
I've tried changing the mouse scrolling value from 250~100 and it doesn't seem to do anything.
So sorry for the inconvenience, and i do hope to find a fix for it soon.

**Comment by Masuzu** [comment]
Hello,
I took note of the request, but usually it is more of a client side issue caused by the windows mouse settings used: https://support.microsoft.com/en-gb/help/14206/windows-7-change-mouse-settings

I use these settings:
![image](https://user-images.githubusercontent.com/5464705/55261198-2dca0e00-5262-11e9-8d9b-b2f703dd6688.png)

**Comment by Kokkujin** [comment]
Ah Alright i will try it out thanks

**Comment by Rkdheishins** [comment]
i had the same problem happen to me to, usually when the page loads it takes a split second to load the summon fully so the curser thinks its in a different location, try using an ability first and more then likely itll know exactly where the summons are not that the page has fully loaded
