### ISSUE TITLE
Calibrating and summon refresh

### ISSUE THREAD

**Issue by ItsKatsura** [Masuzu/ZooeyBot#1128]
Hi I'm still really new to these bots. Majority of the time my bot wouldn't even go through the calibrating phase even though I followed all the requirements. Even when it does get past the phase, when I get to the summon page the mouse would move to the bottom of the screen and repeatedly change the size and never select a summon. How do I fix this?
![Capture](https://user-images.githubusercontent.com/49734901/56435966-4a2cf980-62a8-11e9-8c5b-8eaefc2e145e.PNG)

**Comment by Masuzu** [comment]
Hello,
Make sure that your browser zoom is set to 100%, and that in-game settings follow these recommendations: https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#additional-configuration-settings.
Otherwise you can use DebugCalibration=true in the ZooeyBot.ini file and check whether the numbers displayed are close to 1 (they should be when the calibration is performed under regular conditions);

**Comment by ItsKatsura** [comment]
Where do you find the version and animation setting? I looked everywhere and cant find it
