### ISSUE TITLE
Can u please reupload the tutorial?

### ISSUE THREAD

**Issue by cahya0307** [Masuzu/ZooeyBot#1159]
Im sorry to ask this but on newbie in this and kinda stupid if i didnt see the tutorial step by step with my eyes

I try open the demos but they said ur YouTube account already suspended so i can't see the demos

**Comment by zappky** [comment]
You can try to post your question here. We can try to help you along for now. 

The most common mode you would use is eventmode ,which allows you to bot a certain quest continuously.
So i suggest go and try to read documentation about it and try it out. 

Afterwards, try out treasure eventmode, which is same as eventmode ,but specifically for quest that requires treasure mat to start such as GW. 

Lastly, try out custom schedule,which the strong point is the ability to set the bot to repeat a number of quest to repeat a certain number of time.  Best for Daily grind and rotb

The rest of the stuff at the configuration file is basically just adjusting the bot's behavior or for debugging.

**Comment by cahya0307** [comment]
I already try read the tutorial but im really newbie in this , so how to run the bot script?

**Comment by cahya0307** [comment]
I can't understand , and why after 3/3 initializing then i commanded to go quest page and bot stuck on calibrating

**Comment by zappky** [comment]
Scripting is done in lua script. It can be easily written using notepad in txt file(text file). Just write your codes in txt file, and then save as .lua, or just rename the extension to .lua after saving in txt file.
After you have done your script, reference(a more techical way of saying "to use") your script by providing the directory location to "LuaScript" parameter in the config file,accordingly in the correct section, eventmode or whatnot.

if you dont dunno what is lua and coding,  pls do google Lua scripting, in google and learn some "coding" basic ,otherwise zooey bot is pretty much useless to you. Forunately, even the most basic, brute force code is enough for most of the botting situation.

Calibration problem is a very recurring problem that new user faces. Its solution can be found in faq. Pls refer to that. 
Bascially,make sure your computer is using 100% scaling,not 125% or whatever.
Use the 2 blue diamond for the gbf scaling , the graphic quality ,i.e lite mode or not, doesnt matter. Turn on the browser Dev console ,and run zooeybot.

**Comment by cahya0307** [comment]
Okay thanks
