### ISSUE TITLE
Frame acceleration is safe for use or not?

### ISSUE THREAD

**Issue by i-Grey** [Masuzu/ZooeyBot#1168]
Sorry for asking silly question. I just wonder that frame acceleration is 100% safe for use or not.
I didn't use Viramate before but it seems that FPS hack or something on Viramate isn't safe for using.

What about this one?

**Comment by Masuzu** [comment]
Hi,
This is one of the reasons why I hinted that this new feature was more for "adventurous" people. I had several alt accounts using it for a whole month with no issues. As long as Cygames is paranoiac about minor UI overlays (like, err, Viramate), it is free real estate.

**Comment by samuelljacksonn** [comment]
For my profile, I kept the refresh timer for ougi and the timing for skills the same, just so that I don't run into actions going too fast, so so far the frame acceleration has helped in terms of preventing long running skills.
I'm hoping that the lock out time for summons is the same as skills because I've stopped refreshing on summons. I hope they can't tell the difference between Summon -> Fast refresh -> action vs Frame accelerate summon -> action.

Also, any chance we can get frame acceleration to work in Listener mode or something? so that we can use it for manual tasks like Arcarum?

**Comment by samuelljacksonn** [comment]
> Hi,
> Very good question! This is one of the reasons why I hinted that this new feature was more for "adventurous" people. I had several alt accounts using it for a whole month with no issues. As long as Cygames is paranoiac about minor UI overlays (like, err, Viramate), it is free real estate, but they keep logs... Keep them busy hunting ghosts or fighting scalability issues \ _/

Have your alt accounts ever been banned before? I got a ban on an account the day after enabling fps acceleration. Maybe its one of those things that can only be seen through their spot checking? I never went afk, never missed a captcha.

**Comment by Masuzu** [comment]
> Also, any chance we can get frame acceleration to work in Listener mode or something? so that we can use it for manual tasks like Arcarum?

I have no plans to do so, https://gbtools.azurewebsites.net/CombatSniffer/en/Home does exactly this.

Regarding my alt accounts, none of them so far. They are one year+ old accounts.
