### ISSUE TITLE
Bot keep using Soul Balms when ap refilling

### ISSUE THREAD

**Issue by Vatar** [Masuzu/ZooeyBot#1181]
Hello, 

I'm using the latest release of zoeey bot from this repo, 3.8.3, whenever i run out of AP while using the bot, it'll go to consumables then spam use soul balms till 99ep then get stuck, is there a solution to this behaviour? it seems to target the 3rd item in consumables which happens to be the soul balm.

**Comment by Masuzu** [comment]
Hi, 
This could be due to extensions changing your in-game zoom or layout. Make sure you do not use Chrome mobile device emulator either.
There was a similar case a few days ago where someone had an extension which removed some of the tabs on the supply screen.

**Comment by Vatar** [comment]
I've used the bot on a fresh win7 install with only the coordinates addon, the size of the game is at 2 .. setting as it's the only one which got past the calibration phase; perhaps there's an issue with my game settings?

**Comment by Masuzu** [comment]
Your supply items screen should look like this:
![image](https://user-images.githubusercontent.com/5464705/58739749-dd0e9700-8403-11e9-9b4f-cebeeeb651f7.png)

Reintroducing the "quick AP refill" feature (compared the riskless AP refill in the last versions) for the very low percentage of users who still somehow manage to face related trouble could be an option otherwise.

**Comment by Vatar** [comment]
I haven't had this issue anymore with the newest versions, thanks
