### ISSUE TITLE
has the turn/stage logic changed again?

### ISSUE THREAD

**Issue by xerance** [Masuzu/ZooeyBot#1238]
Hello noticed, that the turn counter doesn't reset after each stage, is this intentional cause if i recall right its suposed to reset every new stage in multistage battles?

edit: stage in question: bzzt extreme

**Comment by Masuzu** [comment]
Hello,
It could be possible due to ingame changes, not following recent version updates.
https://discordapp.com/invite/JaNR87n

**Comment by sam-f-owens** [comment]
Hey xerance it's been doing this to me for multibattle fights for a while. I've been using the numbers["variable_name"] variables to just keep track of turns myself. At the top I initialize them for however many battles I'm going to fight, in this case 3, because battle 1 uses turns properly. 
```
if battle == 1 then 
	if turn == 1 then
		numbers["turn_fix2"]=1              --keeps track of battle 2
		numbers["turn_fix3"]=1		    --keeps track of battle 3
        ...
end
```
Then for other battles I use 
```
if battle == 2 then
     if numbers["turn_fix2"] == 1 then        --these replace the turn == x 
          --turn 1 stuff
     end
     if numbers["turn_fix2"] == 2 then     --these replace the turn == x 
          --turn 2 stuff
     end
     ...
     numbers["turn_fix2"] = numbers["turn_fix2"]+1     --these progress the turn counter
end
```
Just use a different turn_fix (or whatever variable name) variable for every fight. A bit tedious, but works for now.
