### ISSUE TITLE
Extension Id Generator not working?

### ISSUE THREAD

**Issue by nyaonyao56** [Masuzu/ZooeyBot#200]
Hi, I don't know if it was my sister touching my computer or not during the run but when I got home my account was fine until i played 2 raids by myself where I got suspended for 3 hours (not too big of a deal).

So I tried to regenerate the extension id just to be on the safe side again but when I run it, it just crashes with a system unauthorized exception.

**Comment by Masuzu** [comment]
Hi,

When you use the bot, make sure not to play at the same time (whether it's other raids requests or poker). I know of people who had issues because of this.
As for https://github.com/Masuzu/ZooeyBot/wiki/Regenerating-your-Zooey-extension-ID, doesn't it work?

Or did you mean that you can't run ZooeyBotExtensionIdGenerator.exe?
You will need Microsoft .NET Framework 4.5.2 installed.

**Comment by nyaonyao56** [comment]
@Masuzu Hi, 

Hmm, yeah I think my sister just touched my computer while I was away so something must've happened. Because she told me she used my computer while the bot was running.

In regards to the extension ID, I run the generator and it just gives me that exception, I do have .NET Framework 4.5.2 installed as well. If it is admin issues how would I resolve this? I have full admin access on my computer?

**Comment by Masuzu** [comment]
This happens when you try the program tries to update the file while it has not the correct permissions to do so.
You should close all your browser windows first (so that the files in the zooey-bot-extension folder) are not considered as "in use" then relaunch the program as an admin (right click, execute as admin).

**Comment by nyaonyao56** [comment]
Run as admin did the trick. No idea why I didn't do that in the beginning, thanks!
