### ISSUE TITLE
GW problem

### ISSUE THREAD

**Issue by kg6495** [Masuzu/ZooeyBot#207]
There is a bug that returns to my page when I go to quest screen after running event mode
Fix it please

**Comment by sad1234564** [comment]
I figured it out why event mode wasn't working . You are required to calibrate it on the quest page since it is on Event mode. As soon as zoi start entering the url you will be just be directed to mypage. What you need to do is after you are directed to the mypage go to the GW page and enter the link your self then zoi will now play assuming you didn't close it.

**Comment by Masuzu** [comment]
Thanks @sad1234564 !
