### ISSUE TITLE
About silence, again

### ISSUE THREAD

**Issue by Einhalkzt** [Masuzu/ZooeyBot#216]
since this gw boss have silence
the bot will stuck if said chara got silenced
it'll try a few times  and then refresh , repeat
it'll keep on refreshing
for now i use enemy hp script to just stop using any skill after boss hp reach a certain % (where it usually cast the silence)

is it possible to make the bot check if a chara is silenced
or just to make it close the "skill cannot be used at the moment" dialog box and go on with the script instead of refreshing?

thx

**Comment by Masuzu** [comment]
Hi,

Normally, the bot won't get stuck but try unnecessarily to reuse the skill while it can't up to maxNumRetries.
I will see what I can do something about it.

**Comment by Masuzu** [comment]
For now, you can simply use Viramate, the skill simply won't be cast an no skill menu won't even be displayed:
In the picture below, Siegfried is trying to cast his second skill but is silenced.
![](https://i.imgur.com/Yij1ow6.png)

**Comment by Nassy1121** [comment]
Sorry for jump in.
I also face same stuck problem when character skill is silence.
And I'd like to try to avoid stuck by using clarity herbs.
But I can't detect that the character skill is silence or not and can't write script.

Would you let me know how to use clarity herbs suitable?

Thanks,

**Comment by Dreamfinal** [comment]
This problem is solved by using a variable check.
And
UseClarityHerbOnPartyMember (1)
After that, Gran uses Clarity.

I hinted about that.
Enemy_1.hp_percentage <= 25
And
Enemy_1.charge_diamonds == 0

I will not paste code.
Because you want to understand the work of the bot.

Let's see, good luck

https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

**Comment by Masuzu** [comment]
Hi everyone,

You can now detect if a character is affected by a skill sealing debuff and act accordingly as shown here:
https://github.com/Masuzu/ZooeyBot/issues/220

Some enhancements and quality of life Lua script helpers will be provided later on to make use of this new feature more easily but you will get the gist of it as shown there.

Otherwise, as @Dreamfinal mentioned, that is an excellent suggestion too!
(https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#potions-use)

**Comment by Masuzu** [comment]
You can now do this with https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(playing-with-status-effects)
