### ISSUE TITLE
Stuck At Calibrating

### ISSUE THREAD

**Issue by StanFusion** [Masuzu/ZooeyBot#217]
I tried following the faq side, but couldn't solve the issue. So i wandering if it could be my screen resolution being the issue.I  cant make it any bigger.

**Comment by Phucie** [comment]
I too seem to be stuck at calibrating now since last night. The cursor just flickers a bit when it tries to calibrate and doesnt move on, anyone happen to have a work around? I don't know what I did to change it but it was working fine yesterday

**Comment by Hexadecimalism** [comment]
Same issue. Scaling on browser and monitor are set to 100%

**Comment by Masuzu** [comment]
Hi, what mode are you using?
If you use the treasure event mode to farm Nightmare 90 modes, you will need to set `Difficulty=gw-day-2-nm-90`.

**Comment by StanFusion** [comment]
Hi, yea im using treasure event mode  to try and farm ex.

**Comment by Hexadecimalism** [comment]
I'm using event mode for farming EX.

**Comment by Phucie** [comment]
I was using treasure mode properly, the bot just wouldn't calibrate anymore
like normal. It just stays stuck there, I didn't change any settings when
this issue started appearing which is why I am confused, either zooeybot or
chrome.

On Aug 20, 2017 2:26 PM, "Masuzu" <notifications@github.com> wrote:

Hi, what mode are you using?
If you use the treasure event mode to farm Nightmare 90 modes, you will
need to set Difficulty=gw-day-2-nm-90.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Masuzu/ZooeyBot/issues/217#issuecomment-323613095>, or mute
the thread

**Comment by Phucie** [comment]
I currently am using those settings as well. I was using this fine for a couple weeks and now I can't figure out why it is stuck calibrating, when I click toggle device toolbar to make it replicate a phone, then the bot finally takes control of my mouse again but if I don't it just stays dead still....And you can't play it when you toggle the device toolbar anyways.

**Comment by Masuzu** [comment]
If I am not mistaken, the scaling of the elements in the page changes when you switch to the Chrome phone emulation mode.
My animation settings option is set to Standard and my Resolution settings option is set to Standard. It has never been tested with High and low resolution settings.

**Comment by Masuzu** [comment]
@StanFusion Please do not use the Treasure event mode to farm the EX mode during Guid wars. It won't work. Use the Event mode instead and refer to https://github.com/Masuzu/ZooeyBot/issues/206
