### ISSUE TITLE
Crash on Xeno Sagitarius Extreme on 1.18.3

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#230]
Still crashed. I was trying to use Viramate now (was worried the error because I don't use viramate)
I dunno about ABCDEF that was written before every action, but only on 3rd battle
![still error](https://user-images.githubusercontent.com/31296536/29686815-86950ec4-8944-11e7-903d-2ea0c2540c4f.png)

**Comment by Sundaerae** [comment]
and here's the script that I use in xeno sagitarius ex

DisableChargeAttack()
if character_2.charge_gauge > 50 then
	character_2:UseSkill(4)
end
if battle == 1 then
	character_3:UseSkill(3)
end 
if battle == 2 then
	character_1:UseSkill(2)
	character_1:UseSkill(4)
	character_2:UseSkill(2)
end
if battle == 3 then
	if (enemy_1.charge_diamonds > 0) then
		character_1.UseSkill(1)
	end
	character_1:UseSkill(2)
	character_1:UseSkill(3)
	character_1:UseSkill(4)
	character_2:UseSkill(1)
	character_2:UseSkill(2)
	character_2:UseSkill(3)
	if (enemy_1.charge_diamonds == 3) then
		Summon(6)
		character_4:UseSkill(1)
		character_4:UseSkill(2)
		character_3:UseSkill(2)
		character_3:UseSkill(1)
		character_3:UseSkill(3)
		character_4:UseSkill(3)
		EnableChargeAttack()
	end
	if turn > 4 then
		EnableChargeAttack()
	end
end
Summon(5)
Summon(3)
Summon(4)
Summon(2)

**Comment by Masuzu** [comment]
Interesting. One thing is sure for now, it is not related to your Lua script in any case.

**Comment by Masuzu** [comment]
Please replace your ZooeyBot.exe with this custom version provided below:
[ZooeyBot.zip](https://github.com/Masuzu/ZooeyBot/files/1250274/ZooeyBot.zip)

Instead of crashing, you should now have an error message displayed and a file named debug2.txt will be created. Should this happen, it would help a lot if you could post here the contents of this file and the last messages you get in the console window. Thank you in advance.

**Comment by Sundaerae** [comment]
I turned off the `ReloadPageOnLastBattle` . No debug.txt on original 1.18.1.
Then I replaced the ZooeyBot.exe (and it said 1.18.2a), run it again, still crashed
![error on 1182](https://user-images.githubusercontent.com/31296536/29695869-70847126-896f-11e7-98e1-a58488d9635b.png)

and I don't see debug.txt nor debug2.txt
![no debug](https://user-images.githubusercontent.com/31296536/29695927-bdc7c6c2-896f-11e7-98ea-c5f0ae34c834.png)

**Comment by Nassy1121** [comment]
I also faced crash problem.
As per situation, it happens when some of party member is caught debuff.
I attached log.( Copy from console window)

Thanks,

[log.zip](https://github.com/Masuzu/ZooeyBot/files/1251380/log.zip)

**Comment by Masuzu** [comment]
@Nassy1121 I identified the issue with the debuff list retrieval and weird characters, thank you for reporting this bug. It will be fixed in version 1.18.2.

@Sundaerae It's really weird. I do not run into any issues on my side with this event boss. I'll still release a version fixing @Nassy1121 's bug and adding another check in case the lua script fails to be loaded.

**Comment by Sundaerae** [comment]
so I tried using the same lua script to fight ordinary sagitarius. And the same thing happened.
But when I remove all the 3rd battle script, making it only auto attacked, everything works fine.
I'm currently investigating which line is causing the problem

**Comment by Sundaerae** [comment]
I think the problem is Gravity. I have this code:

if battle == 3 then
character_1:UseSkill(3)
	if (enemy_1.charge_diamonds == 0) then
		character_3:UseSkill(2)
	end
	if (enemy_1.charge_diamonds == 1) then
		character_3:UseSkill(1)
	end
	if (enemy_1.charge_diamonds == 2) then
		character_3:UseSkill(3)
	end
end

on the first turn, I use Gravity, then Zooey use conjunction. This is correct.
on the 2nd turn, the Sagitarius have 1 charge, so Zooey supposedly use Resolution, but she didn't. The bot skipped to attack phase instead.
Same goes for the 3rd turn. Just attacking
But this problem doesn't happen on combat that only have 1 battle, like nm.
And, combined with me using > 0 conditional or stall (which also change the enemy charge diamond number), maybe the number goes out of bound.
I do think the problem being the charge_diamond number was fetched incorrectly, thus behave strangely with the .lua script

**Comment by yuayumia** [comment]
Crashed at 1.18.3
It is the language setting of jp
It seems to have crashed trying to get Strong Armed (強圧) debuff

**Comment by Nassy1121** [comment]
@Masuzu 
I still faced crash issue at 1.18.3.
This time, character 3 get paralyze debuff.
(Attached log.)

BTW, does zooeybot have any debug log option?
Currently I get log from terminal window.

Thanks.
[log.zip](https://github.com/Masuzu/ZooeyBot/files/1253420/log.zip)

**Comment by Masuzu** [comment]
Sorry for the late reply and detailed feedback. Will investigate

**Comment by Masuzu** [comment]
From what I gather, excluding the incorrect number of charge diamonds handling, if the issue was in the script, the error would have been caught. From the issue #234, I would tend to think that it's due to the part following the Lua script parsing (finding the attack button) which causes the issue and seemingly random crash.
@Nassy1121 Not yet but I will really consider adding one.

**Comment by Masuzu** [comment]
@Nassy1121 I am very surprised with the output of your console since the Japanese character display was fixed in the version 1.18.3. Maybe it is related to your language settings. https://social.technet.microsoft.com/Forums/windowsserver/en-US/728d6169-07fa-4e93-8a41-f9fa6dd8d9d9/displaying-japanese-in-english-command-prompt
Regardless of this issue, I will test again the debuff retrieval while the Xeno Saggitarius event is still ongoing.

**Comment by Nassy1121** [comment]
@Masuzu 
Thanks for your report.
I'll wait for your feedback and updates.

**Comment by Masuzu** [comment]
@Nassy1121 I was sure I addressed the debuff retrieval issue in the version 1.8.3. Actually it was not!
This time, with the version 1.8.4, it should be fixed. Please let me know if you still run into the issue.

**Comment by Nassy1121** [comment]
@Masuzu 
Thanks for your updates.
Currently I don't faced crash issue when enabled "RetrieveStatusEffects".

**Comment by Masuzu** [comment]
That's good then, thank you for the feedback!
