### ISSUE TITLE
Optime Slave mode time

### ISSUE THREAD

**Issue by BakaPhoenix** [Masuzu/ZooeyBot#24]
I'm trying to get the most run per minute as possible so set 
`DoNotWaitForServerResponse=true`
`MinWaitTimeInMsAfterAbility =700`
And set slave acc to wait and main to kill.
This way is pretty fast but there a very long time (compared to the rest) during the `Main account proceeding to result page` and `Main account returning to lobby room`.
Is possible to reduce this?

**Comment by Masuzu** [comment]
https://www.youtube.com/watch?v=9EIDg5WM1VU
In some cases (I have pinpointed why it happened but could not find how it is possible for this to happen), all the messages sent from the slave window are "ignored". This results in the slave refreshing the page, then waiting for the result window with the XP and RP earned to appear, before refreshing the main account window. If this happen, unfortunately, I have to restart the bot.
It should go smoothly as in the video above under normal conditions.

**Comment by BakaPhoenix** [comment]
I made it run many times now but the main acc don't refresh as fast after slave set up the next quest.
Might me my computer then? It run a i7 3770k.

**Comment by Masuzu** [comment]
I do not think so. It works smoothly even with low end computers. Maybe it is just a ping issue?
Japanese people are known to refresh their page from 2 to 3 times faster than people from US or EU.
In my case I lose 3 seconds when the page is loading and between 4 and 5 after pressing the start button.

**Comment by BakaPhoenix** [comment]
If i run manually the room i'm pretty fast but the time after the slave set quest and main acc enter the lobby is way too long compared to the rest

**Comment by Masuzu** [comment]
I remember trying to make the main account enter the lobby room at the same time as the slave was setting the quest. However, doing so, sometimes the main account would have to refresh the page because the quest was still being set while the main account would re-enter the lobby room, thus losing some seconds.
If you have another series of actions to do it when you slime manually I'm always a buyer for such things!

**Comment by BakaPhoenix** [comment]
When i manually run slime i basically refresh when kill
-paste room link to slave as soon load rp and exp
-use viramate last quest button
-paste room to main
-ready and start

Probably there are faster way to do it

**Comment by Masuzu** [comment]
I feel like I do the same thing, the last quest button being the same thing as setting the slave quest.
With my Internet connection and ping I hardly take more than 2 seconds to rejoin the lobby from the result page :_:

**Comment by BakaPhoenix** [comment]
Maybe is the `main account proceding to result page` that takes time? i don't really know how the bot is scripted but maybe if you make that run on same time as slave setting quest and make the `load lobby trigger` only after slave have loaded quest correctly.

**Comment by Masuzu** [comment]
This is what is done and how it is supposed to run as shown in the video above.
However, there was a bug which has just been fixed in version 1.2.0 which caused a significant slowdown on the result page processing stage, which caused the main account to wait for the slave account result page before refreshing: https://github.com/Masuzu/ZooeyBot/issues/25

**Comment by BakaPhoenix** [comment]
Oh I see, I was using 1.1.3 so was that. Thanks for fixing it
