### ISSUE TITLE
Hell mode is not work.

### ISSUE THREAD

**Issue by NzString** [Masuzu/ZooeyBot#252]
@Masuzu 
(Use 1.18.6 version)
I use this settings, but I can't start event hell.
am I doing wrong?
check please. thank you.

```
# Use this special event mode to automate farming of events stages which require a certain number of items to be hosted, such as Guild War nightmare modes.
[TreasureEventMode]
Enabled=true
TreasureEventUrl=http://game.granbluefantasy.jp/#event/treasureraid059
Difficulty=vh
ActionPointCost=20
TreasureEventModeScript=Scripts/text.lua

NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/721111/3
NightmareModeScript=Scripts/texth.lua
NightmareModePreferredSummons=Shiva,Athena_1
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=true
# Normally I use false.
```

**Comment by Masuzu** [comment]
Hi,

You set `NightmareModeAvailableAtStart=true` meaning that the hell mode has already spawned and that the bot will navigate immediately to `http://game.granbluefantasy.jp/#quest/supporter/721111/3`
I tested it with this setup and it does indeed proceed immediately to the hell mode, if the hell mode spawned. Otherwise you can't start the hell mode.

**Comment by NzString** [comment]
I try new ini file, now I can join hell mode.

Can you check my ini file? I don't know what is different.

[ini.zip](https://github.com/Masuzu/ZooeyBot/files/1279335/ini.zip)

**Comment by Masuzu** [comment]
Good news then!

You can check yourself the differences here:
https://www.diffchecker.com/
