### ISSUE TITLE
script issue 

### ISSUE THREAD

**Issue by okamijackie** [Masuzu/ZooeyBot#261]
i am not sure if i am correctly writing this script because the bot wont respond to it and just keep attacking     this is the script i am trying to use if battle == 1 then
  character_4:UseSkill(2)
  character_4:UseSkill(1)
  character_2:UseSkill(3)
end
i am using notepad ++ and saving it as a lua file.

**Comment by Hexadecimalism** [comment]
I suggest using character names and specifying that they are alive. This will save you a lot of headaches. Here's a sample of what my script looks like
`--Cagliostro--
if character ["Cagliostro"] ~= nil then
	characters ["Cagliostro"]: UseSkill(1)
	if turn >=3 then
		characters ["Cagliostro"]: UseSkill(3)
	end
end`
This forces the script to ignore character positions and instead pay attention to what character is in play. The "~= nil" is an HP check. So it's basically checking to see if this character exists and is alive. The second line tells it to use Cagliostro's first skill whenever it's up.
The third line tell it that if it is the third turn or higher then it can use her third skill. But yeah, try using character names instead of character positions and be sure to add the health check.

**Comment by okamijackie** [comment]
how would i set this up for  other characters i use?

**Comment by Hexadecimalism** [comment]
Replace "Cagliostro" with the character's name (I assume you're playing in english) and edit the rest as you see fit. This lets you ignore the character's position and lets you add the entire team.

**Comment by okamijackie** [comment]
the zooey bot keeps saying: battle 1 turn 1 0 commands were enqueued

**Comment by Hexadecimalism** [comment]
Post your entire combat script please.

**Comment by okamijackie** [comment]
--Zooey--
if character ["Zooey"] ~= nil then
characters ["Zooey"]: UseSkill(2)
if turn >=2 then
characters ["zooey"]: UseSkill(1)
end
end

do you have to edit the name of this a specific way like this : Scripts/skill use.lua?

**Comment by Hexadecimalism** [comment]
Is it a  battle with more than one stage? IE 3 battles?

**Comment by okamijackie** [comment]
Yes

**Comment by Hexadecimalism** [comment]
Did it work without the spaces? Otherwise you might have to specify battle numbers.

**Comment by okamijackie** [comment]
what do you mean by battle turns?

**Comment by Masuzu** [comment]
Hi,

Did you at least make sure that your script is loaded properly?
The script being used is displayed in the console.
https://github.com/Masuzu/ZooeyBot/wiki/FAQ#my-lua-scripts-are-ignored

**Comment by okamijackie** [comment]
In the Zooey bot where is the ini file?

**Comment by ryokage** [comment]
main folder okam

**Comment by okamijackie** [comment]
h

**Comment by Masuzu** [comment]
Closing due to misconfiguration on the user side.
