### ISSUE TITLE
Laptop Stuck at clibrating

### ISSUE THREAD

**Issue by fatboris** [Masuzu/ZooeyBot#322]
the bot was working fine on my desktop, yesterday I tried to copy the whole folder over to my laptop (so that I can keep using my desktop for other stuff) and changed the serial number of my account, my laptop has been having an issue of being stuck at calibrating stage.  I browsed through alot of issue list and none of them worked yet.  

Im about to give up debugging on my laptop, my question is can you let me change my serial number again instead of waiting 4 more days (gw would be over by then)?  Thanks

**Comment by Masuzu** [comment]
Hi,
I can do that, I will notify you when it's done.
Does it say "Hooked to Home button" in the console? If not, all the time, whether it is a laptop or not the issue is your windows DPI scaling settings (especially if you are using Windows 10).
https://www.tenforums.com/tutorials/5990-change-dpi-scaling-level-displays-windows-10-a.html describes how to set the scaling to 100% for instance for Windows 10.

For Windows 7, it's in the control panel -> Appearance and Personalization -> Display:
This is what I use on my Windows 7 laptop:
![](https://i.imgur.com/4dIWss9.png)

**Comment by fatboris** [comment]
Thanks, that solved the problem.
I thought it was the webbrowser's zoom to 100%.
