### ISSUE TITLE
Add feature to request backup

### ISSUE THREAD

**Issue by Hedova928** [Masuzu/ZooeyBot#482]
With the recent introduction of features to automate hosting high HP raids such as Xeno raids, Impossible difficulty story raids, and Rise of the Beasts EX+ raids, is there any plan to support requesting backup for these raids since they're difficult or impossible to clear solo, or at least much more time consuming than they need to be? Would be nice to have the ability to trigger the backup request based on timer/turn counter/party wipe.

**Comment by Masuzu** [comment]
Hi,

I do not plan to add such a feature for Zooey Bot, for now. For high end players those raids are still a piece of cake to solo. Maybe later on.

**Comment by agesa** [comment]
I absolutely second this.  I can spend 10-15 minutes soloing Agni for a 9x multiplier and possibly die near the end, causing the bot to fail to repeat; or I can use skills turn 1, request backup, and get a 2 minute clear with an 8.6x multiplier.  I don't think primal grids should be a necessity to automate an event vital for progression at all stages of the game, newer and middle players moreso than high end players because they have more to buy.  These raids aren't really meant to be soloed to begin with, since you get increasingly marginal returns the more effort you pump into one raid, and entry cost drops with boss HP.

**Comment by Masuzu** [comment]
Addressed as of v3.1.0
