### ISSUE TITLE
Password reset - Email lost?

### ISSUE THREAD

**Issue by filipi159951** [Masuzu/ZooeyBot#488]
hello
my pc broken, and now i got a new...
but i'm trying to login on zooey bot page, and it give me a password error
when i ask about the recover password, the email don't come :/
what can i do?

**Comment by filipi159951** [comment]
![image](https://user-images.githubusercontent.com/31833213/34911550-d765eee8-f8b3-11e7-8750-dfc80e930acc.png)
It never come, and i already bought the license, it have 14 days more :/

**Comment by Masuzu** [comment]
Hello,
If the email address originally associated with your account is not a correct email address then you won't receive any email. Otherwise, make sure that the mail was not deleted by your mailbox filtering rules.
If you think that your email was mistyped and want me to change it to another email, let me know. I can do that too.

**Comment by filipi159951** [comment]
I would like you to change it please, i think i mistyped it @-@

The GW is coming and i need the zooey to get some weapons 😣

i don’t know the email i typed on it, but if you can change it to: filipiaugusto97@gmail.com

**Comment by Masuzu** [comment]
Hmm if the email you used initially is completely different from this one this will be hard to make the change.
If you still have the previous serial number you are currently using, please post the first 10 or 20 characters so I can find the associated account again.

**Comment by filipi159951** [comment]
I remembered the password and the email, thanks man, your message help me alot ❤️
