### ISSUE TITLE
Slave On refresh loop

### ISSUE THREAD

**Issue by BakaPhoenix** [Masuzu/ZooeyBot#49]
I already opened a issues but got closed was #41 
I still have this problem on 1.4.2
Bot runs fine but sometime got on loop. 
I got a ss but i dunno how can you replicate the problem sometime i can run a full room without it looping but others it loops every 2-3 runs.

**Comment by Masuzu** [comment]
In this screenshot, that the Chrome window on the left which kept refreshing, is that right?
[Removed screenshot as you room ID appeared in the console]

**Comment by Masuzu** [comment]
[Edit] Actually, I am pretty surprised.
End of turn 1: both windows navigate to the result page.
Unfortunately the slave window took way longer than normal to reload and Zooey tries to process the second turn of the battle.
With the version 1.4.2, you should not be stuck anymore and a few seconds you should see a message `Slave proceeding to result page` in green in your console, but I did not see anything like this. What keeps bothering me is that the page keeps being refreshed instead of Zooey being simply... stuck.
Would you mind sharing your slave account lua script please (if any)?

**Comment by BakaPhoenix** [comment]
my slave lua script is just the default swordmaster script but without the use of skill (it basically wait for main acc to oneshot the slime)

**Comment by Masuzu** [comment]
Oh by the way, if you do not have the DevTools window docked either at the bottom or at the right side of each Chrome Window, you **will** start having issues after 30 minutes or so.
The Network request history **has** to be cleared regularly.

**Comment by BakaPhoenix** [comment]
Thanks for the tips.
How do i clear the network request history? Just by docking the dev window?

**Comment by Masuzu** [comment]
Yes and updating the related parameter Devtools down under the general section, depending on your docking position.
