### ISSUE TITLE
Extreme Trial farming does not start

### ISSUE THREAD

**Issue by lv4hypocrite** [Masuzu/ZooeyBot#511]
I've recently setup Zooeybot as per instructions, with Animation and Browser settings as recommended.
However, when trying to start Extreme Trial farming, the bot seems to stop working.
![image](https://user-images.githubusercontent.com/35573015/35109983-c80f4198-fc45-11e7-91c3-307073aa9f11.png)
I've tweaked with the settings a little bit, setting Viramate use to True and Event to False, but otherwise everything else is untouched.

As a test, I decided to try Event to True and set the event raid to Aurora Trial and managed to get it to run but it stops at battle 2 with the last line saying Battle 2 / -1.
![image](https://user-images.githubusercontent.com/35573015/35110452-d3e16d06-fc46-11e7-9704-ee4b368b4fde.png)

The script I'm using is just a blank script. I read from an earlier line in the config.ini that having a blank script just make Zooeybot autoattack, but is that not the case for event mode or am I doing something wrong?

**Comment by Masuzu** [comment]
Hello,
Thank you for reaching out.
Make sure you configure properly the DevTools window. the network tab should look like this:
![image](https://user-images.githubusercontent.com/5464705/35120264-db8a7326-fc97-11e7-9187-dc5dda681e52.png)

In your case, the bad configuration makes it so that Zooey is completely unresponsive to anything that happens in the game, resulting in this "issue".
