### ISSUE TITLE
Slave bot crash on 1.5.1

### ISSUE THREAD

**Issue by i-Grey** [Masuzu/ZooeyBot#52]
It works normally in 1.4.1 but after upgrading to 1.5.1 it crash suddenly when the cursor  is trying to locate character's ability.
I didn't do the slime blasting but I select the stage 8-1 by using 3rd skill of Threo.

Everything is fine in 1.4.1 but it crash on 1.5.1

Best Regards.

**Comment by i-Grey** [comment]
One more thing.
Preferred Summons stuck on reloading too.

I'm trying to use it on UNITE AND FIGHT and it stucks at reloading when there's no preferred summons found.

**Comment by Masuzu** [comment]
Hi,
That's surprising since I do not remember making any change in this side. Maybe you were lucky (or unlucky) enough to find yourself into this situation. Did the character selection pass at least? I use Viramate shortcuts so I am much more likely to overlook issues regarding non Viramate skill usage.
The reloading issue is fixed on my side. I will release a fix later today.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/51

**Comment by i-Grey** [comment]
Masuzu, Thanks for updating new version.

I haven't tried the newer one yet but I would like to give you more information about my case.

The problem occur after cursor selected the character and trying to locate the skill position.
For my case, mouse point select Threo and then moving likely to click on her 3rd skill but before clicking it, program crashed suddenly.

I didn't use Veramate though. 

I will try again soon to see there's any problems or not. (At that moment, I was trying to use slave bot for leveling Drum Master job.)

**Comment by Masuzu** [comment]
Hi @i-Grey ,

The crash following the selection of the ability to use should not happen anymore with v1.6.4:
https://localhost:44300/ZooeyBot/en/Home/PatchNotes
