### ISSUE TITLE
Zooey bot stuck on not ready skills

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#531]
Hi, old versions of Zooey bot didn’t have this issue, when the bot try to use skill and couldn’t use for some reasons , it’s will hold wait for someone to click the pop msg, like Beatrix 3rd skill when it’s no enough hp , u get msg no enough hp then stop here. Sometimes it’s work fine sometimes it’s stop.

**Comment by Masuzu** [comment]
Hello,
It still works as before. Zooey will perform up for `MaxNumRetries` the action if it failed (make sure you disabled the Viramate auto close popup feature as well)
Otherwise it is the responsibility of the script designer to check conditions such that `ìf characters["Beatrix"].hp_percentage < ... then `
