### ISSUE TITLE
Zooeybot stops after rerolling summons with trial battle

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#588]
Twice now, after resetting summons using a trial battle, zooeybot stops and plays the captha notification sound. This was while farming NM90. I pasted the log leading up to it below:

New page loaded: http://game.granbluefantasy.jp/#event/teamraid036
Quest cost 30
Not enough action points to start the quest, refilling AP.
New page loaded: http://game.granbluefantasy.jp/#event/teamraid036/supporter/725571/1
Listing available summons
Quest cost -1
No preferred summon found. Rerolling summon using trial battles.
New page loaded: http://game.granbluefantasy.jp/#quest/supporter/990041/17
Listing available summons
Quest cost -1
No preferred summon found, selecting misc summons tab
Loading party selection script party_selection.lua
New page loaded: http://game.granbluefantasy.jp/#raid/<removed>
New page loCadoedm: bhtatpt:/ /gmamoe.dgrean blauecfatntiasvy.ejp
#raid/<removed>
List of active debuffs
1609 Thick Skin

Retreating from the battle.
New page loaded: http://game.granbluefantasy.jp/#quest
New page loaded: http://game.granbluefantasy.jp/#event/teamraid036
Quest cost 30
New page loaded: http://game.granbluefantasy.jp/#event/teamraid036/supporter/725571/1
Listing available summons
Quest cost -1
Preferred summons were found while it should not be the case!

**Comment by Beedrills** [comment]
Yeah I'm getting the same thing. At first it was any time she got to the summon screen, but I figured out that was because I had the Favorites tab enabled in Viramate. Turned that off and she worked until she attempted to trial battle reset the summons. Kitanda, eeeh? Kitanda.

No preferred summon found, selecting dark summons tab
Loading party selection script party_selection.lua
New page loaded: http://game.granbluefantasy.jp/#raid/212821910
Combat mode active
New page loaded: http://game.granbluefantasy.jp/#raid/212821910
List of active debuffs
1609 Thick Skin

Retreating from the battle.
New page loaded: http://game.granbluefantasy.jp/#quest
New page loaded: http://game.granbluefantasy.jp/#event/teamraid036
New page loaded: http://game.granbluefantasy.jp/#quest/supporter/725551/1
Listing available summons
Quest cost 35
Preferred summons were found while it should not be the case!

**Comment by ryokage** [comment]
@Masuzu

**Comment by Masuzu** [comment]
It is a false positive related to summon rerolling. This will be addressed before the start of the next round.

**Comment by Hexadecimalism** [comment]
Came to post this, glad to see it's an issue that is tracked.

**Comment by Masuzu** [comment]
This is now addressed in v2.9.2.
Good luck with your first GW round.
