### ISSUE TITLE
No active window with Granblue Fantasy Found - Can't Start

### ISSUE THREAD

**Issue by eichisama** [Masuzu/ZooeyBot#618]
Can't start Bot giving error as in the screenshot. Help.

![error](https://user-images.githubusercontent.com/33214703/36948548-7891f7a0-2017-11e8-9063-0a7a276f51c9.JPG)

**Comment by Gepyon** [comment]
Getting this issue too with my granblue chrome tab opened with all the correct screen settings and a default ini file. This is my first time getting an issue doing the same steps as previous versions.

**Comment by Masuzu** [comment]
Hello,
If you use the English settings (by default `Language=en` in the ini file), then in your Task manager you should see something along these lines:
![image](https://user-images.githubusercontent.com/5464705/36965974-8f42b6f8-205b-11e8-9280-4134a05d6e47.png)
I am not sure whether it could be caused by a Windows locale issues. Does it lead to the same error running using admin settings?

**Comment by Gepyon** [comment]
Changing the language to en has fixed my issue. Thank you.

**Comment by eichisama** [comment]
Yes, it's working now, however I can't get it work, after navigation to the quest, It done nothing :P
