### ISSUE TITLE
Slime infinite refreshing in lobby after 1 round

### ISSUE THREAD

**Issue by rockysilver** [Masuzu/ZooeyBot#653]
I am using Chromium 67.0.3366, the bot was working fine on the first slime, after using the skill in master, both slave and master refresh at the same time, both went to result screen, refresh again and both ended up lobby. Then master just keep refreshing nonstop.  

```

Slave mode - Initialization
Initializing slime-blasting mode
Calibrating
Successfully hooked to the Home button
Clear network request history
Calibrating
Successfully hooked to the Home button
Clear network request history
Initialization complete, Zooey is now proceeding to autopilot mode.
294 remaining AP
Quest cost 10
Slave window - New page loaded: http://game.granbluefantasy.jp/#raid_multi/---------
Slave window - New page loaded: http://game.granbluefantasy.jp/#raid_multi/---------
New page loaded: http://game.granbluefantasy.jp/#coopraid/room/-----------
Combat mode active
Processing turn 1 of slave account
Waiting for Attack button to be active
New page loaded: http://game.granbluefantasy.jp/#raid_multi/------------
List of active buffs
1036_9 Bounty

Loading Lua script C:\----------------\Scripts/slime_blasting_slave.lua
Use summon at position 6
Script loaded
Processing turn 1 of main account
Waiting for Attack button to be active
Loading Lua script C:\-------------\Scripts/slime_blasting_master.lua
Select character at position 4 (Threo)
Use skill at position 3
Script loaded
The battle ended.
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid

```

**Comment by Masuzu** [comment]
Hello,
I won't say that this does not look familiar since I tried to reproduce this issue after encountering it a few days ago.
If I understand well, Zooey is still stuck in combat mode (even though `The battle ended.` is displayed), then refreshes continually the master (slave ?) window, resulting in a series of `Refresh` messages in the console.

**Comment by calvinhyang** [comment]
I don't know if it's related, but I'm getting an issue where zooeybot is just stuck in "Slave proceeding to result page" and doesn't do anything anymore. Doesn't try to go to fallback procedure either which hasn't happened to me before. This is after one round of sliming, and then sends both master and slave to result page and just hangs there forever. 
Sliming was working for me fine yesterday so not sure what the problem is

**Comment by meteoshower** [comment]
Hello Zooey 2.11.3 still cant use slave right? after blast slime battle mymain account head back to room and keep refresh but my slave account is stuck at result page

**Comment by Shamool** [comment]
Idk about that but I can slave perfectly fine?

**Comment by devvah** [comment]
I just had the same problem, no matter what I did bot ended up refreshing infinitely, I even readied and started fight manually then bot caught on for one or 2 fights and got back to refreshing even more aggressively, turns out turning off viramate solves the issue.

However another thing is that compared to when I slimed last half coop and solo coop now, bot is incredibly slow both using viramite and without it, wait time between actions is too big.

**Comment by devvah** [comment]
I just had the same problem, no matter what I did bot ended up refreshing infinitely, I even readied and started fight manually then bot caught on for one or 2 fights and got back to refreshing even more aggressively, turns out turning off viramate solves the issue.

However another thing is that compared to when I slimed last half coop and solo coop now, bot is incredibly slow both using viramite and without it, wait time between actions is too big.

**Comment by Masuzu** [comment]
Hello,
There should be no issue.
The configuration plays a great part and all the steps described on https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting), including the last section, should be followed in that exact same order.
I managed to get between 5 and 6 clears per minute with Zooey and JP ping, after the latest changes.
