### ISSUE TITLE
After calibration, start menu gets stuck open and bot wont choose a summon

### ISSUE THREAD

**Issue by minotopo2000** [Masuzu/ZooeyBot#670]
As ia said in title once i open the bot, and finishes calibration, it get  stuck in summon selection and wont choose one because start menu is on the way. It also happens when bot randomnly calibrates in between runs.
![image](https://user-images.githubusercontent.com/31526112/37620767-ed06345e-2b9b-11e8-8677-4c0f2c566621.png)

**Comment by IZEROII** [comment]
You need to make sure  is ChromeDevToolsWindowDockedOnTheRight=true

I'm assuming it is not because there is no reason the mouse should be moving to the start menu.  Additionally devtools need to be on 'Network' tab and not 'Elements' as  you have screen capped. 

This all really doesn't matter because the bot is fairly bugged right now so while you need to make those corrections in all likelihood, you are going to run into an issue anyway until @Masuzu addresses the issues.

**Comment by Masuzu** [comment]
Hello,
As said in the post above it is just a misconfiguration issue on your side. I added an explicit note this time:
https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#first-run
