### ISSUE TITLE
Zooey running period

### ISSUE THREAD

**Issue by williamvun** [Masuzu/ZooeyBot#724]
@Masuzu 
How long can we run Zooey bot until the their system triggers?
Is there any recommendation hour for running?
Any person can answer this. I just wanna know since the main page doesn't mention anything about it.

**Comment by Shamool** [comment]
Random, verification captcha comes randomly. However, I found my safe period to be around 3 hours.

**Comment by williamvun** [comment]
3 hours huh. Anyone tested for long period like 12 or more?

**Comment by Shamool** [comment]
Nope, I've never needed to run it that long, though the bot pauses on captcha either ways so all you'd have to do is go check on it every hour or so.

**Comment by williamvun** [comment]
The bot sometimes went click Windows Start button. Is this normal or rather what it is doing?

**Comment by Shamool** [comment]
I can make a guess that you may have forgot to reflect in your zooey bot configurations file "ChromeDevToolSetToRight" or something that follows along the lines of that to true. Hence it calibrates the the bottom where it can't find the dev tools and clicks windows button instead.

**Comment by williamvun** [comment]
First time user. And already set it to true. thanks.

**Comment by Masuzu** [comment]
Hello,
Please make sure to configure properly the parameter `ChromeDevToolSetToRight` as mentioned in the first message written in red in the console to avoid these reported misclicks, as @Shamool pointed out.
There is no general rule of thumb regarding when the captcha can appear or not (it has been 2 guild wars since it last happened on my side. I got one during slime blasting on a 3rd session following 2 one hour sessions in a row but that's it during the previous half AP co-op event but that's it).
