### ISSUE TITLE
Eternal calibrating....

### ISSUE THREAD

**Issue by Seininsm** [Masuzu/ZooeyBot#736]
I do not speak English well Please understand

It was good until 30 minutes ago.

However 

anti macro sound->(There was no image...only sound)->Eternal calibrating Repeat...

https://imgur.com/XSippie  << This is the same

I changed resolution setting...

but

It was not fixed. 

plz...help me

**Comment by lamewood** [comment]
I've got the same issue. But I noticed, that my window in Chromium is smaller than in Chrome - even though I used the same size-settings (the 2 dot option)

**Comment by Masuzu** [comment]
Hello,
Everything seems fine. Make sure that your other Chrome window has no Granblue Fantasy tab active. Maybe a Chrome zoom issue?
![image](https://user-images.githubusercontent.com/5464705/38518434-23876c6c-3c3d-11e8-8a19-0b6615d39977.png)
Also, did you make sure to set the language settings to 'en' instead of 'jp' in the configuration file?

I will add some additional info messages in the next release.
