### ISSUE TITLE
Any chance we could get a phone notification when captcha pops up?

### ISSUE THREAD

**Issue by xerance** [Masuzu/ZooeyBot#737]
Would it be possible to make the bot send a msg to your phone when captcha pops up? 

If not, any chance you could add this feature? Using something like PushBullet perhaps?

**Comment by Masuzu** [comment]
Hello,
This would require a lot of effort but that would be possible. I have not experienced a lot of captcha these days, if at all, apart from the coop mode.

**Comment by xeratzy** [comment]
Well, could technically be used for other stuff too, like schedule/coop finishes, if the bot stops due to error and so on. Not limited to one thing.

Some kind of external notification system would be neat, even if its just a msg sent on email or w/e. especially for people whom work/study or accessing their computer via remote.

**Comment by Koraxor** [comment]
Seems like we're getting captchas again, any progress on this? Personally, I have a job that I can't watch the bot all day so I can't really bot if I'm not home since there's no way to catch the captcha in a timely manner and I'd just get banned. Would be nice to get a notification so I could just remote in and verify.
