### ISSUE TITLE
Random gibberish

### ISSUE THREAD

**Issue by IgarashiDai** [Masuzu/ZooeyBot#739]
So after updating to v2.11.8, sometimes this happens:

![image](https://user-images.githubusercontent.com/37836106/38581198-635faf8c-3d0c-11e8-9942-f6a1b8538c46.png)

Instead of saying page X loaded, it shows some random gibberish and then the bot crashes... any idea what might be causing this?

EDIT: this is the error that shows up before it crashes.
![image](https://user-images.githubusercontent.com/37836106/38583364-0ff8bbc0-3d13-11e8-8357-fbb7891a7f24.png)

**Comment by Masuzu** [comment]
Hello,
It is not that it crash. The random gibberish is just due to the logger system and is not impacting at all.
Your script has an error, such as accessing a charater on a front line which is not there anymore, resulting in this error. It is a user side issue with the script used: you should add if conditions to prevent such scenarios.

**Comment by IgarashiDai** [comment]
No one died tho...
