### ISSUE TITLE
infinity loop clicking the nm selection icon

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#762]
hello Mazusu, 

i got some issue 
after the bot finished with the nm 95 raid
it would back to URL home page
and the problem start when opening the nm selection between nm 90 and nm 95
the bot click the nm 95 when the connection goes down for a seconds 
and then stuck while trying to clicking the nm 95 icon with "now loading" near the icon
solved if manually reload the page

how to refresh the page while the bot stuck at clicking the nm 95 after few seconds?

**Comment by Masuzu** [comment]
Hello,
Please reread
`# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'impossible' (introduced since the "Right Behind You" event), 'xeno-raid' (for the level 100 Xeno raid), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100
Difficulty=gw-day-4-nm-90`
