### ISSUE TITLE
coop not using any skills

### ISSUE THREAD

**Issue by readmynameplease** [Masuzu/ZooeyBot#766]
after starting the coop the main account seems not using any skills at all it's just there idle and doing nothing the main and slave accout got scripts that are working when not on slave mode

**Comment by readmynameplease** [comment]
here is the screenshot btw its stuck in this 

http://prntscr.com/jaotcz

**Comment by Masuzu** [comment]
Hello,
![image](https://user-images.githubusercontent.com/5464705/39390267-5858c888-4a92-11e8-9d11-f5e2604c872f.png)
This shows that you did not initialized properly the 2 extensions, You should only get messages "New network request received". It could be due to https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)#other-remarks or the loading order.
