### ISSUE TITLE
Serial number issue again

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#813]
Last few days had this issue . Tried to fix it by restart the pc . Still giving me another serial than the one generated by site. Few days ago I updated what i got changed in the bot folder. Then after 2 days got the issue back and thanks u opened the 4 days restriction.  Anyway I don't wanna change it to the new one then get back asking me for the old serial. Anyway this issue happened twice after I click the new patch not on pop msg. Then after I close it this happen. It was happening to me before but it's solve when close and reopen the bot but seem there something came up. And many getting this issue

**Comment by doskoi4** [comment]
same

**Comment by Masuzu** [comment]
If you are using rogue Windows version that may happen.
I do not consider it an issue at all since you can fix it on your side, and the procedure to apply is still 
 the same as the one described in: https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-get-an-unregistered-user-error-message
If the serial_number.txt contents change regularly, it is an issue with your operating system and configuration, not on my side.
