### ISSUE TITLE
New anti-bot protection?

### ISSUE THREAD

**Issue by soufflenote** [Masuzu/ZooeyBot#834]
Hi! I was wondering, what's the status on the new automation detector that people have been talking about? I've been avoiding using Zooey for a couple weeks now just in case, and haven't seen any messages from the developer here addressing the issue or new patches. Is this project dead? Just want to know before I renew my subscription. ^^ Thanks!

**Comment by IZEROII** [comment]
It's not a new anti-bot or anything.  The bot is working as intended.  It stops and notifies when either of the two bot detectors make their presence.  What does this mean, you can't leave the bot unattended for hours at a time.  You have to check in on it.  

I will say this, the heavy bot detection screens are during GW.  Outside of GW, you get a captcha every blue moon.  You hear the alert, you input the captcha, get back to bot grinding.  

I don't see there being any new implementation because the only new thing would be if a new screen made an appearance like the summon page red button confirmation three GWs ago.  Other than that, it's not going to input captchas for you.  It is immediately stopping when a captcha comes up and the user is getting in trouble for not inputting a captcha fast enough which is a red flag but they can't prove anything because there is no bot "like" activity post captcha generation.

**Comment by soufflenote** [comment]
Ah, I see, my bad! Just got scared looking at that PSA post someone made about two weeks ago, and hadn't heard anything since then. Thanks!
