### ISSUE TITLE
ZooeyBot v2.14.5 crashes constantly

### ISSUE THREAD

**Issue by ModelGTX** [Masuzu/ZooeyBot#895]
Hi there

I got some issues with the latest version of ZooeyBot, just wondering if it is the problem with the program or was the problem lies on my end. 

I was using this lua script to farm xeno cocy ex mode

if battle == 1 and turn == 1 then
  character_3:UseSkill(1)
  character_3:OnPartyMember(4):UseSkill(2)  
  character_1:UseSkill(2)
  character_2:UseSkill(2)
  character_2:UseSkill(1)  
end

if battle == 2 and turn == 1 then
  character_3:UseSkill(3)
end

if battle == 3 and turn == 1 then
  SelectTarget(2)
  character_1:UseSkill(3)
  character_4:UseSkill(3)
end

if battle == 3 and turn == 2 then
  character_4:UseSkill(2)
  character_2:UseSkill(3)  
  character_1:UseSkill(1)
end

if battle == 3 and turn == 3 then
  character_4:UseSkill(1)
end

Zooey was launched properly and the script was loaded properly
However after the **first battle ended** Zooey would **crash** without any warning message pop up (usually if the script wasnt typed properly an error message would appear) 

EDIT: the last message it appears before the crash was "Proceed to next stage"

just wondering if the error was due to the script itself or zooey. 

I tried the same script on older version such as v2.14.1 (that was the lastest one I've got before the v2.14.5) and the script would work properly without any crashes, BUT the turn and battle logic was messed up (because the bug was only fixed in v2.14.3 and above) so making my script obsolete 

So wonder if anyone has similar issue and any help to get around it? 

Thanks 

EDIT 2: uploaded the image, ignore the red no response line because i was trying to open up snipping tool to take the screeny
![image](https://user-images.githubusercontent.com/38687875/44322262-a2ed8d80-a4a0-11e8-9e9f-ea421bb3bf00.png)

**Comment by Masuzu** [comment]
Hello,

I am quite surprised that you ran into this since there is no change regarding this part between v2.14.1 and v2.14.5 did not change anything related to battle stage change.
"Proceed to next stage" is followed by a "Battle X/<total number of battles in the current quest>" message and all that happens between is just waiting for the result button.
So you should also sometimes have had the same issue with v.2.14.1.
However, thank you for reporting this, it let me spot a bug which could lead in the exact same crash that you experienced.

I will address it within the next 12 hours.

**Comment by Masuzu** [comment]
v2.14.6 was released earlier with a bugfix for this error.
