### ISSUE TITLE
New place of Captcha

### ISSUE THREAD

**Issue by giauten** [Masuzu/ZooeyBot#960]
Within the update today, GBF has implemented more places for captcha screen
I'm not sure how many new places in total, but this one is at loading screen

![image](https://user-images.githubusercontent.com/43314003/47730369-981b5a00-dc94-11e8-8b98-be075f3c46d2.png)

Seem we will be banned if using Zooey
So please come back and keep track with new anti-bot system

**Comment by Chololoco13** [comment]
How long were you playing?
Captcha notification worked?
Google Translate-

**Comment by warbaulten** [comment]
I read that they added anti bot measures in this patch which also shut down viramate (which may possibly be due to viramates own user safeguards that activate after updates). Not sure if it's limited to just the captcha's but personally I'm not using zoeey until its confirmed still safe and undetectable. Babysitting while using Zoeey I don't mind but I don't know if it may refresh past captcha or somehow miss it or other features.

**Comment by meteoshower** [comment]
Can say now zooey  don't safe anymore.

**Comment by i-Grey** [comment]
@Masuzu Can you confirm about this issue? This time of Scenario Event is really fascinated for Botting.

**Comment by MegaBlues** [comment]
Does the notification sound go off when the new captchas appear?

**Comment by ariaanaa** [comment]
did anyone still playing with bot? it is confirm safe?

**Comment by i-Grey** [comment]
@ariaanaa I'm still using it carefully. I mean, I use ZooeyBot on Laptop while I sit the next to it. Still no Captcha appear at all so I can't judge anything yet.

**Comment by warbaulten** [comment]
So I have been running on alt for 7 hours with one captcha (which was on support summon select) and i still had sound for it with no ban(yet). No guarantee but may be safe. Kate (maker of viramate) said cygames is now tracking shortcuts (skill icons you could click without clicking portrait first) so may be better off playing it safe and seeing what else cygames may be tracking. Who knows, If they want they could be stalling bans to catch as many people as possible without them warning others. Will update if my alt gets ban hammer.

**Comment by GBFUSER1993** [comment]
Had anyone know what happen to @masuzu? He hadn't update the bot not reply any issue for a long time

**Comment by warbaulten** [comment]
He seems to have been MIA for a month on this site but gbtools twitter is still tweeting (Even about recent viramate being down) so not sure if he's busy irl or doesn't check often or doesn't care. 

Update on alt is I did another 4 hours of testing did not get another captcha yet and still no ban. Not guaranteeing it's safe but it does appear to be for now; just make sure you play it with laptop nearby/computer or gbf sounds on so you can hear when it stops playing if zooeybot sound does not prompt. I'm just somewhat sceptical and cautious still since it seems illogical to create bot countermeasure that do not counter one of the most well known bots for granblue. My personal opinion is risk is low but if you're on 1-2 strikes already (Cygames has a 3 strikes you're out policy for those who don't know) wait a while longer. Maybe after guild wars since that's when I'd ban people if i was cygames and was waiting to send a message to botters.

**Comment by i-Grey** [comment]
Here's an update from my side.

Yesterday, Captcha alert 1 time. It's the usual one at the Summon page. After that I had continued for around 2 hours and no Captcha alert at all.
Today, Captcha came up after grinding for around 2-3 hours. Still the usual one at the Summon page.

I'm agree with warbaulten about the safety for the current time but I can't saying that it's 100% safe.
For my suggestion, just normal farming without using Viramate and make sure that you can deal with Captcha instantly is promising.

With the absence of the owner. We, users, need to help each others like this.

Anyway, Do you see someone whom use new Viramate and got banned yet?

**Comment by Rkdheishins** [comment]
i've been using vira everyday now and i've been ok
on a side note i just received a new capcha*
the one for gw that says please click here something something
i hesitated and just clicked it just because i remember we had to do that for last gw
but on a odd note only had zoey going for about an hour this time and that appeared

**Comment by GBFUSER1993** [comment]
Update from my side. The bot warns me few minutes ago about a captcha appearing, not the usual one. Before the summon selection page, it told me to press vertify to confirm In not a bot. Anyone please be aware

**Comment by zappky** [comment]
seems like Cygames updated Anti-cheat code once again

**Comment by Chololoco13** [comment]
Where is Masuzu? Is it safe to "play" after the "update"? Viramate is dead again

**Comment by Masuzu** [comment]
Deal all,

Both the aforementioned verification summon button and captcha after picking a summon are no different from the ones which we had in the past (both during GW and regular events or regular quests), and still trigger a sound alert.
The anti-cheat code, which is obfuscated, has not changed regarding the checks it performed (apart from the fact that user-side actions such as clicks are not sent anymore back to the servers): only the obfucation "seed" changed, resulting in a slightly different obfuscated anti-cheat code whenever CyGames feels like regenerating the anti-cheat code, but its behaviour has not changed.
