### ISSUE TITLE
Should I renew my license?

### ISSUE THREAD

**Issue by Chololoco13** [Masuzu/ZooeyBot#966]
The gw is close.
My license expired a week ago and I do not know if I should renew it.
The game has been constantly updated, these updates have me restless.
Viramate is dying after each update, I do not know if these measures can affect zooey bot.
There is not a new zooey bot update since September. zooey bot is dead? 
You will use zooey bot in the next gw?
Sorry for my English. Google translator

**Comment by Youhyou** [comment]
Sadly to tell but I  just got banned for 1 month, second time. The first time was 3 hours ten days ago because of ignoring the captcha too long. However, this time I had not even seen a captcha or heard the warning sound while I was working beside. I got my last 3 years account permaban in this summer but due to my carelessness for the same reason everytime, ignoring the captcha while sleeping or something else. It was my own fault. 

But this time even if I was stay by side with my botting machine, I got banned. I don't know if this is the last chance for this account, but getting banned without alerting did affect my confidence for using it.

**Comment by xerance** [comment]
@Masuzu do zooey detect the apparently new captcha? see https://github.com/Masuzu/ZooeyBot/issues/960

**Comment by zooeyjapan** [comment]
Thanks for the reply Masuzu, you have my support.

**Comment by Masuzu** [comment]
@xerance , Unless I am mistaken, this is actually not different than the regular captcha at the summon selection page. You will also find some remarks (https://github.com/Masuzu/ZooeyBot/issues/960) about the anticheat changes which resulted in Viramate shutting down a few times in the past few days.
